pull_request_rules:
  - name: Automatic merge author pr on checks pass
    conditions:
      - status-success=Check Code Quality
      - status-success=Run unit tests
      - status-success=ktlint
      - status-success=Try build application
      - base:develop
      - author:VovaStelmashchuk
    actions:
      merge:
        method: merge
  - name: Automatic merge GoodReadMeBot
    conditions:
      - status-success=Check Code Quality
      - status-success=Run unit tests
      - status-success=ktlint
      - status-success=Try build application
      - base:develop
      - author:GoodReadMeBot
    actions:
      merge:
        method: merge
  - name: Automatic merge external pr on checks pass
    conditions:
      - status-success=Check Code Quality
      - status-success=Run unit tests
      - status-success=ktlint
      - status-success=Try build application
      - base:develop
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  - name: Automatic merge dependabot
    conditions:
      - status-success=Check Code Quality
      - status-success=Run unit tests
      - status-success=ktlint
      - status-success=Try build application
      - base:develop
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      merge:
        method: merge
  - name: delete head branch on closed pull requests
    conditions:
      - merged
    actions:
      delete_head_branch:
